
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 112
#define YY_END_OF_BUFFER 113
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[447] =
    {   0,
        0,    0,    0,    0,    0,    0,  113,  111,  109,  110,
      110,   89,  111,   85,   95,  111,  104,  105,   83,   81,
      106,   82,   99,   84,   15,   15,   91,  107,   74,   68,
       75,   90,  108,  108,  102,  103,   96,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  100,   94,  101,   88,    5,
        2,    3,   11,    8,    9,   11,  110,   98,    0,   18,
        0,   93,   73,    0,   19,    0,   71,   86,   69,   87,
       70,   16,    6,    1,   72,   16,   15,   16,    0,   15,
        0,    0,    0,    0,   15,    0,   78,   76,   97,   77,

       79,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,   58,  108,  108,  108,  108,  108,  108,
       53,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,   34,  108,
      108,  108,  108,  108,  108,   92,    4,   10,    7,   18,
        0,   18,    0,    0,    0,    0,    0,    0,    0,    0,
       16,    0,   16,    0,   15,   15,    0,    0,   16,   16,
        0,   15,   15,    0,   15,   80,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,   59,  108,   21,  108,  108,

      108,   26,  108,  108,  108,  108,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,   64,
      108,   51,  108,  108,  108,  108,    0,    0,    0,    0,
        0,    0,    0,    0,   16,   16,    0,   16,   16,   16,
       16,    0,    0,    0,   15,   15,    0,    0,   15,   15,
        0,    0,    0,   15,    0,  108,  108,  108,  108,  108,
       55,  108,  108,  108,  108,  108,   54,  108,  108,  108,
      108,  108,  108,  108,  108,   14,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  108,  108,   22,
      108,  108,   13,   35,   24,  108,  108,   37,    0,    0,

        0,    0,    0,    0,    0,    0,   16,    0,   16,    0,
        0,    0,    0,   16,   16,    0,    0,  108,  108,  108,
      108,   60,   65,   23,  108,  108,  108,  108,  108,   44,
       20,  108,  108,  108,   33,  108,  108,  108,  108,  108,
      108,  108,  108,   27,  108,  108,   63,  108,  108,   57,
        0,    0,    0,    0,    0,    0,    0,    0,   16,   16,
        0,  108,  108,   52,  108,  108,  108,  108,  108,  108,
      108,   30,   45,  108,  108,  108,  108,   40,  108,   62,
       39,   28,  108,   50,  108,  108,   17,    0,    0,    0,
        0,  108,   25,  108,   56,   32,   49,   66,  108,   29,

       42,  108,  108,  108,  108,  108,  108,  108,    0,    0,
       43,   61,  108,  108,   36,   31,  108,  108,  108,   48,
        0,    0,  108,   41,  108,   47,  108,    0,   67,  108,
       38,    0,  108,    0,   46,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   12,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   29,   29,   30,   31,   30,
       32,   32,   32,   32,   32,   33,   32,   32,   32,   34,
       32,   32,   35,   32,   32,   32,   32,   36,   32,   32,
       37,   38,   39,   40,   41,    1,   42,   43,   44,   45,

       46,   47,   48,   49,   50,   32,   51,   52,   53,   54,
       55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        5,    6,    1,    1,    1,    1,    1,    1,    6,    6,
        6,    7,    8,    9,    7,    7,    1,    3,    1,    1,
        9,    6,    5,    6,    6,    6,    5,    7,    7,    7,
        7,    8,    7,   10,    7,    9,    7,   10,   10,   10,
       10,    7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[472] =
    {   0,
        0,    0,   68,   70,   72,   74,  983,  984,  984,  984,
      979,  955,   73,  984,   72,   72,  984,  984,  954,   69,
      984,   68,   69,   80,   96,  145,  984,  984,   74,  953,
       75,  984,    0,  913,  984,  984,  984,   50,   63,   81,
       50,   55,  102,   66,  922,  921,   89,  919,   98,  928,
      109,  113,  914,   83,   54,  984,  904,  984,  984,  984,
      984,  968,  984,  984,  967,  952,  984,  984,  139,  962,
      192,  984,  984,  958,  984,  161,  984,  984,  984,  984,
      984,  186,  984,  984,  984,  236,  207,  984,  223,  984,
      950,  243,  128,  949,    0,  250,  984,  984,  984,  984,

      937,    0,  904,  903,  902,  905,  913,  898,  124,  915,
      914,  901,  907,  892,  893,   93,  899,  896,  894,  890,
        0,  128,  893,  901,  885,  881,  891,  896,  897,  139,
      897,  136,  884,  896,  881,  886,  881,  145,    0,  158,
      888,  875,   72,  882,  871,  984,  984,  984,  984,  984,
      271,  196,  209,  259,  280,    0,  313,  284,  302,    0,
      984,  294,  307,  348,  353,  984,  269,  327,  294,  357,
        0,  366,  362,    0,  375,  984,  870,  869,  882,  875,
      884,  879,  878,  879,  864,  862,  860,  877,  875,  871,
      861,  869,  855,  871,  870,    0,  851,    0,  862,  848,

      858,    0,  855,  852,  854,  842,  158,  851,  833,  818,
      820,  817,  830,  814,  827,  811,  811,  811,  802,    0,
      781,    0,  780,  782,  771,  773,  292,  386,  407,  254,
      428,  811,    0,  414,  376,  421,  434,  431,  461,  984,
      466,  479,  469,  117,  488,  984,  513,  503,  497,  984,
      378,  471,  165,  523,  529,  748,  713,  712,  723,  717,
        0,  718,  707,  715,  703,  711,    0,  704,  707,  714,
      707,  698,  715,  704,  682,    0,  683,  694,  690,  685,
      680,  679,  677,  656,  652,  661,  652,  664,  656,    0,
      636,  629,    0,    0,    0,  625,  638,    0,  422,  486,

      544,  270,  533,  562,  583,    0,  577,  551,  613,  568,
      550,  582,  626,  513,  631,  621,  623,  629,  633,  614,
      631,    0,    0,    0,  616,  617,  621,  603,  614,  604,
        0,  588,  595,  594,    0,  573,  560,  575,  572,  571,
      553,  556,  564,    0,  544,  525,  521,  528,  527,    0,
      633,  279,  662,  677,  683,    0,  704,    0,  984,  698,
      672,  560,  530,    0,  513,  500,  486,  483,  482,  458,
      474,    0,    0,  471,  468,  449,  449,    0,  448,    0,
        0,    0,  438,    0,  290,  425,  984,  734,  703,    0,
      414,  407,    0,  419,    0,    0,    0,    0,  418,    0,

        0,  417,  385,  379,  383,  376,  379,  374,    0,  356,
        0,    0,  360,  367,    0,    0,  351,  333,  326,    0,
        0,  325,  337,    0,  317,    0,  319,  348,    0,  316,
        0,  284,  285,  248,    0,  199,  175,  154,  157,  131,
      145,  123,   97,  213,   74,  984,  772,  782,  792,  802,
      808,  816,  823,  826,  828,  830,  833,  838,  841,  850,
      856,  858,  863,  870,  876,  878,  880,  882,  884,  886,
      892
    } ;

static const flex_int16_t yy_def[472] =
    {   0,
      446,    1,  447,  447,  448,  448,  446,  446,  446,  446,
      446,  446,  449,  446,  446,  450,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  451,  451,  446,  446,  446,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  449,  446,
      449,  446,  446,  446,  446,  452,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      453,  446,  446,  454,   26,  446,  446,  446,  446,  446,

      446,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  446,  446,  446,  446,  446,
      446,  449,  449,  449,  449,   71,  449,  446,  446,  455,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      456,  457,  446,  458,  459,  446,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,

      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  446,  460,  460,  449,
      157,  446,  461,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  462,  456,  457,  446,  446,  245,  446,  446,
      446,  463,  458,  459,  254,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  460,  460,

      460,  460,  464,  460,  157,  465,  446,  446,  446,  446,
      462,  462,  446,  446,  446,  463,  463,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      460,  460,  460,  460,  460,  466,  157,  467,  446,  446,
      446,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  446,  460,  460,  468,
      446,  451,  451,  451,  451,  451,  451,  451,  451,  451,

      451,  451,  451,  451,  451,  451,  451,  451,  469,  446,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      470,  446,  451,  451,  451,  451,  451,  446,  451,  451,
      451,  446,  451,  446,  451,  446,  446,  446,  446,  446,
      446,  471,  471,  471,  471,    0,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446
    } ;

static const flex_int16_t yy_nxt[1055] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       26,   26,   27,   28,   29,   30,   31,   32,   33,   33,
       33,   33,   33,   33,   34,   33,   35,    8,   36,   37,
       33,   38,   39,   40,   41,   42,   43,   33,   33,   44,
       33,   45,   46,   47,   48,   49,   33,   50,   51,   52,
       53,   54,   55,   33,   33,   33,   56,   57,   58,   59,
       61,   62,   61,   62,   64,   65,   64,   65,   70,   72,
       75,   78,   80,   66,  444,   66,   82,   82,   82,   82,
       82,   83,  104,   81,   79,  113,   84,   73,   97,   98,

      100,  101,  144,  145,  114,   85,  115,  444,  105,   76,
       71,   86,  121,   87,   87,   87,   87,  106,  116,  122,
      107,  223,  109,  224,  142,   88,   89,  108,   90,  110,
      125,   91,  111,  444,  126,  112,   92,  143,   93,  129,
       88,   89,   88,  117,  150,  173,  173,   90,  191,  127,
      247,  118,  192,  119,  442,  130,  120,  133,  131,   94,
       86,  138,   95,   95,   95,   95,   95,  139,  134,  135,
      140,  136,  247,  137,   88,   89,   71,   90,  158,  158,
      158,  159,  183,  184,  441,   96,  197,  198,  206,   88,
       89,   88,  209,  207,  216,  210,   90,  152,  247,  218,

      153,  150,  217,   82,   82,   82,   82,   82,  440,  154,
      154,  154,  155,  439,  150,  161,  162,  280,  219,  281,
      247,  160,  220,  444,  165,  165,  165,  165,  438,  156,
      161,  162,  161,   71,  153,  168,  445,  168,  153,  166,
      169,  170,  170,  170,  170,  153,   71,  167,  437,  153,
      153,  153,  157,  163,  163,  163,  163,  163,  166,  150,
       87,   87,   87,   87,  150,   88,  164,   95,   95,   95,
       95,   95,  227,  228,  229,  352,  155,  155,  155,  155,
       88,  164,   88,   92,  387,  150,  165,  165,  165,  165,
       96,   71,   75,  227,  228,  229,   71,  230,  230,  230,

      230,  159,  159,  159,  159,  436,  234,  446,  234,  167,
       75,  235,  236,  236,  236,  236,  446,   71,  150,  232,
      232,  232,  232,  240,  163,  163,  163,  163,  163,  435,
      231,  231,  231,  231,  231,  406,   88,  164,  240,  434,
      240,  231,  231,  231,  169,  170,  170,  170,  170,  407,
       71,   88,  164,   88,  231,  231,  231,  231,  231,  231,
      237,  433,  237,  432,  431,  238,  239,  239,  239,  239,
      165,  165,  165,  165,  241,  241,  241,  241,  241,  249,
      249,  244,  430,  429,  428,  166,  240,  427,  300,  301,
      253,  302,  426,  167,  250,  249,  249,  242,  246,  247,

      425,  240,  251,  240,  166,  161,  248,  246,  247,  304,
      301,  424,  302,  250,  423,  255,  422,  246,  251,  420,
      161,  247,  161,  303,  300,  301,  246,  302,  419,  418,
      247,  235,  236,  236,  236,  236,  417,  416,  307,  307,
      307,  307,  307,  415,  303,  305,  305,  305,  305,  305,
      161,  238,  239,  239,  239,  239,  305,  305,  305,  303,
       88,  308,  414,  413,  412,  161,  411,  161,  410,  305,
      305,  305,  305,  305,  305,   88,  408,   88,  309,  309,
      309,  309,  309,  241,  241,  241,  241,  241,  300,  301,
       88,  302,  405,  404,  403,  240,  241,  241,  241,  241,

      241,  310,  247,  244,  247,   88,  242,   88,  402,  312,
      240,  317,  240,  401,  249,  249,  400,  399,  446,  242,
      246,  247,  398,  303,  247,  313,  247,  313,  248,  250,
      314,  315,  315,  315,  315,  446,  446,  251,  253,  246,
      397,  396,  359,  247,  446,  395,  351,  301,  250,  302,
      354,  354,  354,  355,  446,  246,  247,  359,  446,  359,
      394,  446,  446,  255,  300,  301,  393,  302,  307,  307,
      307,  307,  307,  392,  246,  391,  386,  385,  247,  384,
      446,  303,  383,  247,  446,  309,  309,  309,  309,  309,
      312,  308,  382,  356,  307,  307,  307,  307,  307,  303,

      357,  357,  357,  357,  357,  247,  161,  381,  310,  380,
      379,  357,  357,  357,  378,  446,  377,  308,  376,  375,
      374,  161,  312,  161,  357,  357,  357,  357,  357,  357,
      309,  309,  309,  309,  309,  300,  301,  446,  302,  373,
      372,  371,   88,  314,  315,  315,  315,  315,  360,  360,
      360,  360,  360,  310,  247,  370,  446,   88,  369,   88,
      359,  317,  368,  317,  300,  301,  331,  302,  367,  366,
      303,  361,  365,  364,  363,  359,  247,  359,  446,  300,
      301,  362,  302,  350,  349,  300,  301,  348,  302,  360,
      360,  360,  360,  360,  388,  388,  388,  388,  347,  303,

      389,  389,  389,  389,  346,  300,  301,  345,  302,  344,
      343,  198,  361,  342,  303,  360,  360,  360,  360,  360,
      303,  153,  153,  153,  153,  153,  341,  359,  340,  339,
      338,  337,  153,  153,  153,  336,  300,  301,  361,  302,
      303,  335,  359,  334,  359,  153,  153,  153,  153,  153,
      153,  389,  389,  389,  389,  333,  332,  331,  330,  293,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  303,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   69,  318,   69,   69,   69,   69,   69,   69,

       69,   69,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,  102,  102,  102,  102,  102,  102,   74,   75,
       74,  298,  297,  296,  295,   74,  172,  172,  172,  175,
      175,  175,  233,  233,  243,  243,  245,  245,  245,  294,
      245,  245,  252,  252,  254,  254,  254,  293,  254,  254,
      299,  299,  299,  299,  299,  299,  299,  299,  299,  299,
      306,  306,  311,  311,  292,  291,  311,  316,  316,  290,
      289,  316,  353,  288,  353,  287,  286,  285,  284,  353,
      358,  358,  390,  390,   74,   74,  409,  409,  421,  421,
      353,  353,  443,  283,  443,  443,  443,  443,  443,  443,

      443,  443,  282,  279,  278,  277,  276,  275,  274,  198,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  198,  262,  261,  198,  260,  259,  258,  257,  256,
      226,  225,  222,  221,  215,  214,  213,  212,  211,  208,
      205,  204,  203,  202,  201,  200,  199,  196,  195,  194,
      193,  190,  189,  188,  187,  186,  185,  182,  181,  180,
      179,  178,  177,  176,  174,  171,   75,  151,  149,  148,
      147,  146,  141,  132,  128,  124,  123,  103,   99,   77,
       68,   67,  446,    7,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446
    } ;

static const flex_int16_t yy_chk[1055] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    4,    4,    5,    5,    6,    6,   13,   15,
       16,   20,   22,    5,  445,    6,   23,   23,   23,   23,
       23,   24,   38,   22,   20,   41,   24,   15,   29,   29,

       31,   31,   55,   55,   41,   24,   42,  443,   38,   16,
       13,   25,   44,   25,   25,   25,   25,   39,   42,   44,
       39,  143,   40,  143,   54,   25,   25,   39,   25,   40,
       47,   25,   40,  442,   47,   40,   25,   54,   25,   49,
       25,   25,   25,   43,   69,   93,   93,   25,  116,   47,
      244,   43,  116,   43,  441,   49,   43,   51,   49,   25,
       26,   52,   26,   26,   26,   26,   26,   52,   51,   51,
       52,   51,  244,   51,   26,   26,   69,   26,   76,   76,
       76,   76,  109,  109,  440,   26,  122,  122,  130,   26,
       26,   26,  132,  130,  138,  132,   26,   71,  253,  140,

       71,  152,  138,   82,   82,   82,   82,   82,  439,   71,
       71,   71,   71,  438,  153,   82,   82,  207,  140,  207,
      253,   76,  140,  444,   87,   87,   87,   87,  437,   71,
       82,   82,   82,  152,   71,   89,  444,   89,   71,   87,
       89,   89,   89,   89,   89,   71,  153,   87,  436,   71,
       71,   71,   71,   86,   86,   86,   86,   86,   87,  230,
       92,   92,   92,   92,  154,   86,   86,   96,   96,   96,
       96,   96,  151,  151,  151,  302,  154,  154,  154,  154,
       86,   86,   86,   92,  352,  155,  167,  167,  167,  167,
       96,  230,  158,  227,  227,  227,  154,  155,  155,  155,

      155,  158,  158,  158,  158,  434,  162,  302,  162,  167,
      159,  162,  162,  162,  162,  162,  352,  155,  157,  159,
      159,  159,  159,  169,  163,  163,  163,  163,  163,  433,
      157,  157,  157,  157,  157,  385,  163,  163,  169,  432,
      169,  157,  157,  157,  168,  168,  168,  168,  168,  385,
      157,  163,  163,  163,  157,  157,  157,  157,  157,  157,
      164,  430,  164,  428,  427,  164,  164,  164,  164,  164,
      165,  165,  165,  165,  170,  170,  170,  170,  170,  173,
      173,  172,  425,  423,  422,  165,  170,  419,  228,  228,
      175,  228,  418,  165,  173,  251,  251,  170,  172,  172,

      417,  170,  173,  170,  165,  235,  172,  175,  175,  229,
      229,  414,  229,  173,  413,  175,  410,  172,  251,  408,
      235,  172,  235,  228,  299,  299,  175,  299,  407,  406,
      175,  234,  234,  234,  234,  234,  405,  404,  236,  236,
      236,  236,  236,  403,  229,  231,  231,  231,  231,  231,
      236,  237,  237,  237,  237,  237,  231,  231,  231,  299,
      238,  236,  402,  399,  394,  236,  392,  236,  391,  231,
      231,  231,  231,  231,  231,  238,  386,  238,  239,  239,
      239,  239,  239,  241,  241,  241,  241,  241,  300,  300,
      239,  300,  383,  379,  377,  241,  242,  242,  242,  242,

      242,  239,  243,  245,  252,  239,  241,  239,  376,  243,
      241,  252,  241,  375,  249,  249,  374,  371,  248,  242,
      245,  245,  370,  300,  243,  247,  252,  247,  245,  249,
      247,  247,  247,  247,  247,  248,  248,  249,  254,  245,
      369,  368,  314,  245,  255,  367,  301,  301,  249,  301,
      303,  303,  303,  303,  248,  254,  254,  314,  248,  314,
      366,  255,  255,  254,  304,  304,  365,  304,  308,  308,
      308,  308,  308,  363,  254,  362,  349,  348,  254,  347,
      255,  301,  346,  311,  255,  310,  310,  310,  310,  310,
      311,  308,  345,  303,  307,  307,  307,  307,  307,  304,

      305,  305,  305,  305,  305,  311,  307,  343,  310,  342,
      341,  305,  305,  305,  340,  312,  339,  307,  338,  337,
      336,  307,  312,  307,  305,  305,  305,  305,  305,  305,
      309,  309,  309,  309,  309,  351,  351,  312,  351,  334,
      333,  332,  309,  313,  313,  313,  313,  313,  315,  315,
      315,  315,  315,  309,  316,  330,  317,  309,  329,  309,
      315,  316,  328,  317,  353,  353,  327,  353,  326,  325,
      351,  315,  321,  320,  319,  315,  316,  315,  317,  354,
      354,  318,  354,  297,  296,  355,  355,  292,  355,  361,
      361,  361,  361,  361,  354,  354,  354,  354,  291,  353,

      355,  355,  355,  355,  289,  389,  389,  288,  389,  287,
      286,  285,  361,  284,  354,  360,  360,  360,  360,  360,
      355,  357,  357,  357,  357,  357,  283,  360,  282,  281,
      280,  279,  357,  357,  357,  278,  388,  388,  360,  388,
      389,  277,  360,  275,  360,  357,  357,  357,  357,  357,
      357,  388,  388,  388,  388,  274,  273,  272,  271,  270,
      269,  268,  266,  265,  264,  263,  262,  260,  259,  258,
      257,  388,  447,  447,  447,  447,  447,  447,  447,  447,
      447,  447,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  449,  256,  449,  449,  449,  449,  449,  449,

      449,  449,  450,  450,  450,  450,  450,  450,  450,  450,
      450,  450,  451,  451,  451,  451,  451,  451,  452,  232,
      452,  226,  225,  224,  223,  452,  453,  453,  453,  454,
      454,  454,  455,  455,  456,  456,  457,  457,  457,  221,
      457,  457,  458,  458,  459,  459,  459,  219,  459,  459,
      460,  460,  460,  460,  460,  460,  460,  460,  460,  460,
      461,  461,  462,  462,  218,  217,  462,  463,  463,  216,
      215,  463,  464,  214,  464,  213,  212,  211,  210,  464,
      465,  465,  466,  466,  467,  467,  468,  468,  469,  469,
      470,  470,  471,  209,  471,  471,  471,  471,  471,  471,

      471,  471,  208,  206,  205,  204,  203,  201,  200,  199,
      197,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      145,  144,  142,  141,  137,  136,  135,  134,  133,  131,
      129,  128,  127,  126,  125,  124,  123,  120,  119,  118,
      117,  115,  114,  113,  112,  111,  110,  108,  107,  106,
      105,  104,  103,  101,   94,   91,   74,   70,   66,   65,
       62,   57,   53,   50,   48,   46,   45,   34,   30,   19,
       12,   11,    7,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,

      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446,  446,  446,  446,  446,  446,  446,
      446,  446,  446,  446
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[113] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "java_lexer.l"
#line 2 "java_lexer.l"
    #include<bits/stdc++.h>
    using namespace std;
    #include "test.tab.h"
    int lines=1;
#line 861 "lex.yy.c"

#line 863 "lex.yy.c"

#define INITIAL 0
#define COMMENT1 1
#define COMMENT2 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 46 "java_lexer.l"


#line 1085 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 447 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 984 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "java_lexer.l"
{BEGIN(COMMENT1);}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 49 "java_lexer.l"
{lines++; 
                       BEGIN(INITIAL);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "java_lexer.l"
{lines++; 
                       BEGIN(INITIAL);}                       
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 53 "java_lexer.l"
{lines++; 
                       BEGIN(INITIAL);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "java_lexer.l"
{/*ignore*/}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "java_lexer.l"
{BEGIN(COMMENT2); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "java_lexer.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 59 "java_lexer.l"
{lines++;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "java_lexer.l"
{lines++;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 61 "java_lexer.l"
{lines++;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "java_lexer.l"
{/*ignore*/}           
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "java_lexer.l"
{}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "java_lexer.l"
{yylval.lex = new string(yytext); return BOOL_LITERAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "java_lexer.l"
{yylval.lex = new string(yytext); return NULL_LITERAL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "java_lexer.l"
{yylval.lex = new string(yytext); return INT_LITERAL;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "java_lexer.l"
{yylval.lex = new string(yytext); return FLOAT_LITERAL;}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 69 "java_lexer.l"
{yylval.lex = new string(yytext); return TEXTBLOCK_LITERAL;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 70 "java_lexer.l"
{yylval.lex = new string(yytext); return STRING_LITERAL;}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 71 "java_lexer.l"
{yylval.lex = new string(yytext); return CHAR_LITERAL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "java_lexer.l"
{yylval.lex = new string(yytext); return FLOATINGPOINTTYPE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "java_lexer.l"
{yylval.lex = new string(yytext); return INTEGRALTYPE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "java_lexer.l"
{yylval.lex = new string(yytext); return THIS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "java_lexer.l"
{yylval.lex = new string(yytext); return CLASS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "java_lexer.l"
{yylval.lex = new string(yytext); return VOID;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "java_lexer.l"
{yylval.lex = new string(yytext); return BOOLEAN;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "java_lexer.l"
{yylval.lex = new string(yytext); return NEW;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "java_lexer.l"
{yylval.lex = new string(yytext); return SUPER;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "java_lexer.l"
{yylval.lex = new string(yytext); return SWITCH;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "java_lexer.l"
{yylval.lex = new string(yytext); return PACKAGE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "java_lexer.l"
{yylval.lex = new string(yytext); return MODULE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "java_lexer.l"
{yylval.lex = new string(yytext); return REQUIRES;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 84 "java_lexer.l"
{yylval.lex = new string(yytext); return EXPORTS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 85 "java_lexer.l"
{yylval.lex = new string(yytext); return OPENS;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "java_lexer.l"
{yylval.lex = new string(yytext); return TO;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "java_lexer.l"
{yylval.lex = new string(yytext); return USES;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 88 "java_lexer.l"
{yylval.lex = new string(yytext); return PROVIDES;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 89 "java_lexer.l"
{yylval.lex = new string(yytext); return WITH;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 90 "java_lexer.l"
{yylval.lex = new string(yytext); return TRANSITIVE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 91 "java_lexer.l"
{yylval.lex = new string(yytext); return STATIC;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 92 "java_lexer.l"
{yylval.lex = new string(yytext); return PUBLIC;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "java_lexer.l"
{yylval.lex = new string(yytext); return PROTECTED;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "java_lexer.l"
{yylval.lex = new string(yytext); return PRIVATE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 95 "java_lexer.l"
{yylval.lex = new string(yytext); return ABSTRACT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "java_lexer.l"
{yylval.lex = new string(yytext); return FINAL;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "java_lexer.l"
{yylval.lex = new string(yytext); return NATIVE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "java_lexer.l"
{yylval.lex = new string(yytext); return SYNCHRONIZED; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "java_lexer.l"
{yylval.lex = new string(yytext); return TRANSIENT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "java_lexer.l"
{yylval.lex = new string(yytext); return VOLATILE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "java_lexer.l"
{yylval.lex = new string(yytext); return EXTENDS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "java_lexer.l"
{yylval.lex = new string(yytext); return THROWS;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "java_lexer.l"
{yylval.lex = new string(yytext); return VAR;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "java_lexer.l"
{yylval.lex = new string(yytext); return ASSERT;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "java_lexer.l"
{yylval.lex = new string(yytext); return IF;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "java_lexer.l"
{yylval.lex = new string(yytext); return ELSE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "java_lexer.l"
{yylval.lex = new string(yytext); return CASE;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 108 "java_lexer.l"
{yylval.lex = new string(yytext); return DEFAULT;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 109 "java_lexer.l"
{yylval.lex = new string(yytext); return WHILE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 110 "java_lexer.l"
{yylval.lex = new string(yytext); return DO;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 111 "java_lexer.l"
{yylval.lex = new string(yytext); return FOR;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "java_lexer.l"
{yylval.lex = new string(yytext); return BREAK;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "java_lexer.l"
{yylval.lex = new string(yytext); return CONTINUE;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "java_lexer.l"
{yylval.lex = new string(yytext); return RETURN;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "java_lexer.l"
{yylval.lex = new string(yytext); return THROW;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "java_lexer.l"
{yylval.lex = new string(yytext); return TRY;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 117 "java_lexer.l"
{yylval.lex = new string(yytext); return CATCH;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 118 "java_lexer.l"
{yylval.lex = new string(yytext); return FINALLY;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "java_lexer.l"
{yylval.lex = new string(yytext); return INSTANCEOF;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "java_lexer.l"
{yylval.lex = new string(yytext); return EQUALTO;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 121 "java_lexer.l"
{yylval.lex = new string(yytext); return PLUSET;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "java_lexer.l"
{yylval.lex = new string(yytext); return MINUSET;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 123 "java_lexer.l"
{yylval.lex = new string(yytext); return MULTET;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 124 "java_lexer.l"
{yylval.lex = new string(yytext); return DIVET;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 125 "java_lexer.l"
{yylval.lex = new string(yytext); return ANDET;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 126 "java_lexer.l"
{yylval.lex = new string(yytext); return LT;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 127 "java_lexer.l"
{yylval.lex = new string(yytext); return GT;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 128 "java_lexer.l"
{yylval.lex = new string(yytext); return LEQ;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 129 "java_lexer.l"
{yylval.lex = new string(yytext); return GEQ;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 130 "java_lexer.l"
{yylval.lex = new string(yytext); return LEFTSHIFT;}  
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 131 "java_lexer.l"
{yylval.lex = new string(yytext); return RIGHTSHIFT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 132 "java_lexer.l"
{yylval.lex = new string(yytext); return THREEGREAT;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 133 "java_lexer.l"
{yylval.lex = new string(yytext); return PLUS;}   
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 134 "java_lexer.l"
{yylval.lex = new string(yytext); return MINUS;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 135 "java_lexer.l"
{yylval.lex = new string(yytext); return MULT;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 136 "java_lexer.l"
{yylval.lex = new string(yytext); return DIVIDE;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 137 "java_lexer.l"
{yylval.lex = new string(yytext); return MODULO;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 138 "java_lexer.l"
{yylval.lex = new string(yytext); return INCREMENT;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 139 "java_lexer.l"
{yylval.lex = new string(yytext); return DECREMENT;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 140 "java_lexer.l"
{yylval.lex = new string(yytext); return TILDE;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 141 "java_lexer.l"
{yylval.lex = new string(yytext); return NOT;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 142 "java_lexer.l"
{yylval.lex = new string(yytext); return QUEST;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 143 "java_lexer.l"
{yylval.lex = new string(yytext); return COLON;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 144 "java_lexer.l"
{yylval.lex = new string(yytext); return OR;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 145 "java_lexer.l"
{yylval.lex = new string(yytext); return AND;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 146 "java_lexer.l"
{yylval.lex = new string(yytext); return BITOR;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 147 "java_lexer.l"
{yylval.lex = new string(yytext); return BITAND;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 148 "java_lexer.l"
{yylval.lex = new string(yytext); return POW;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 149 "java_lexer.l"
{yylval.lex = new string(yytext); return EQ;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 150 "java_lexer.l"
{yylval.lex = new string(yytext); return NEQ;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 151 "java_lexer.l"
{yylval.lex = new string(yytext); return DOT;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 152 "java_lexer.l"
{yylval.lex = new string(yytext); return LCB;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 153 "java_lexer.l"
{yylval.lex = new string(yytext); return RCB;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 154 "java_lexer.l"
{yylval.lex = new string(yytext); return LSB;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 155 "java_lexer.l"
{yylval.lex = new string(yytext); return RSB;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 156 "java_lexer.l"
{yylval.lex = new string(yytext); return LRB;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 157 "java_lexer.l"
{yylval.lex = new string(yytext); return RRB;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 158 "java_lexer.l"
{yylval.lex = new string(yytext); return COMMA;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 159 "java_lexer.l"
{yylval.lex = new string(yytext); return SEMICOLON;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 160 "java_lexer.l"
{yylval.lex = new string(yytext); return IDENTIFIER;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 161 "java_lexer.l"
{/*ignore whitespace*/}
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 162 "java_lexer.l"
{/*ignore line terminator*/}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 163 "java_lexer.l"
{cerr<<"Illegal character encountered: Lexical Error "<<strdup(yytext)<<endl; exit(1);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 164 "java_lexer.l"
ECHO;
	YY_BREAK
#line 1722 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT1):
case YY_STATE_EOF(COMMENT2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 447 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 447 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 446);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 164 "java_lexer.l"

