
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 111
#define YY_END_OF_BUFFER 112
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[425] =
    {   0,
        0,    0,    0,    0,    0,    0,  112,  110,  108,  109,
      109,   88,  110,   84,   94,  110,  103,  104,   82,   80,
      105,   81,   98,   83,   14,   14,   90,  106,   73,   67,
       74,   89,  107,  101,  102,   95,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,   99,   93,  100,   87,    5,    2,
        3,   11,    8,    9,   11,  109,   97,    0,   17,    0,
       92,   72,    0,   18,    0,   70,   85,   68,   86,   69,
       15,    6,    1,   71,   15,   14,   15,    0,   14,    0,
        0,    0,    0,   14,    0,   77,   75,   96,   76,   78,

      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,   57,  107,  107,  107,  107,  107,  107,   52,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,   33,  107,  107,  107,
      107,  107,  107,   91,    4,   10,    7,   17,    0,   17,
        0,    0,    0,    0,    0,    0,    0,    0,   15,    0,
       15,    0,   14,   14,    0,    0,   15,   15,    0,   14,
       14,    0,   14,   79,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,   58,  107,   20,  107,  107,  107,   25,  107,

      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,   63,  107,   50,  107,
      107,  107,  107,    0,    0,    0,    0,    0,    0,    0,
        0,   15,   15,    0,   15,   15,   15,   15,    0,    0,
        0,   14,   14,    0,    0,   14,   14,    0,    0,    0,
       14,    0,  107,  107,  107,  107,   54,  107,  107,  107,
      107,  107,   53,  107,  107,  107,  107,  107,  107,  107,
      107,   13,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,   21,  107,  107,   12,   34,
       23,  107,  107,   36,    0,    0,    0,    0,    0,    0,

        0,    0,   15,    0,   15,    0,    0,    0,    0,   15,
       15,    0,    0,  107,  107,  107,   59,   64,   22,  107,
      107,  107,  107,  107,   43,   19,  107,  107,  107,   32,
      107,  107,  107,  107,  107,  107,  107,  107,   26,  107,
      107,   62,  107,  107,   56,    0,    0,    0,    0,    0,
        0,    0,    0,   15,   15,    0,  107,   51,  107,  107,
      107,  107,  107,  107,  107,   29,   44,  107,  107,  107,
      107,   39,  107,   61,   38,   27,  107,   49,  107,  107,
       16,    0,    0,    0,  107,   24,  107,   55,   31,   48,
       65,  107,   28,   41,  107,  107,  107,  107,  107,  107,

      107,    0,   42,   60,  107,  107,   35,   30,  107,  107,
      107,   47,    0,  107,   40,  107,   46,  107,   66,  107,
       37,  107,   45,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   29,   29,   30,   31,   30,
       32,   32,   32,   32,   32,   33,   32,   32,   32,   34,
       32,   32,   32,   32,   32,   32,   32,   35,   32,   32,
       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   32,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        5,    6,    1,    1,    1,    1,    1,    1,    6,    6,
        6,    7,    8,    9,    7,    1,    3,    1,    1,    9,
        6,    5,    6,    6,    6,    5,    7,    7,    7,    7,
        8,    7,   10,    7,    9,    7,   10,   10,   10,   10,
        7,    7,    7,    7,    7,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[449] =
    {   0,
        0,    0,   67,   69,   71,   73,  950,  951,  951,  951,
      946,  922,   72,  951,   71,   71,  951,  951,  921,   68,
      951,   67,   68,   79,   94,  142,  951,  951,   73,  920,
       74,  951,    0,  951,  951,  951,   53,   62,   96,   76,
       41,   92,   82,  891,  890,   62,  888,   91,  897,  106,
      123,  883,   77,  104,  951,  873,  951,  951,  951,  951,
      936,  951,  951,  935,  920,  951,  951,  153,  930,  188,
      951,  951,  926,  951,  180,  951,  951,  951,  951,  951,
      192,  951,  951,  951,  198,  231,  951,  240,  951,  918,
      184,  137,  917,    0,  247,  951,  951,  951,  951,  905,

        0,  873,  872,  875,  883,  868,  120,  885,  884,  871,
      877,  862,  863,   47,  869,  866,  864,  860,    0,  125,
      863,  871,  855,  851,  861,  866,  867,  120,  867,   61,
      854,  866,  851,  856,  851,  132,    0,  213,  858,  845,
      182,  839,  828,  951,  951,  951,  951,  951,  272,  189,
      190,  272,  277,    0,  309,  285,  292,    0,  951,  303,
      314,  348,  353,  951,  357,  361,  226,  369,    0,  286,
      377,    0,  368,  951,  827,  840,  832,  839,  834,  830,
      831,  800,  791,  775,  792,  790,  786,  775,  758,  722,
      738,  737,    0,  718,    0,  729,  715,  725,    0,  722,

      719,  721,  709,  220,  718,  708,  707,  709,  702,  715,
      700,  709,  688,  690,  687,  694,    0,  680,    0,  684,
      681,  670,  672,  282,  408,  418,  226,  438,  710,    0,
      411,  318,  431,  416,  395,  467,  951,  472,  501,  408,
      351,  492,  951,  515,  511,  491,  951,  425,  506,  371,
      523,  534,  651,  650,  657,  651,    0,  651,  639,  645,
      629,  637,    0,  630,  632,  638,  631,  622,  638,  626,
      612,    0,  607,  622,  615,  609,  603,  601,  599,  570,
      567,  558,  548,  561,  555,    0,  539,  542,    0,    0,
        0,  534,  546,    0,  492,  511,  549,  251,  551,  573,

      594,    0,  562,  577,  611,  624,  520,  554,  600,  432,
      640,  594,  613,  549,  528,  532,    0,    0,    0,  512,
      513,  514,  499,  507,  498,    0,  485,  461,  460,    0,
      457,  444,  458,  456,  456,  417,  420,  429,    0,  422,
      409,  406,  405,  397,    0,  663,  410,  668,  672,  692,
        0,  712,    0,  951,  705,  696,  397,    0,  374,  360,
      359,  349,  345,  336,  355,    0,    0,  349,  347,  306,
      312,    0,  311,    0,    0,    0,  295,    0,  176,  296,
      951,  744,  700,    0,  284,    0,  297,    0,    0,    0,
        0,  272,    0,    0,  263,  249,  242,  246,  236,  231,

      194,    0,    0,    0,  161,  148,    0,    0,  142,  126,
      115,    0,    0,  121,    0,   84,    0,   97,    0,   78,
        0,   40,    0,  951,  781,  791,  801,  811,  817,  825,
      832,  835,  837,  839,  842,  847,  850,  859,  865,  867,
      872,  879,  885,  887,  889,  891,  893,  895
    } ;

static const flex_int16_t yy_def[449] =
    {   0,
      424,    1,  425,  425,  426,  426,  424,  424,  424,  424,
      424,  424,  427,  424,  424,  428,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  429,  424,  424,  424,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  427,  424,  427,
      424,  424,  424,  424,  430,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  431,
      424,  424,  432,   26,  424,  424,  424,  424,  424,  424,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  424,  424,  424,  424,  424,  424,  427,
      427,  427,  427,   70,  427,  424,  424,  433,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  434,  435,
      424,  436,  437,  424,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  424,  438,  438,  427,  155,  424,  439,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  440,
      434,  435,  424,  424,  242,  424,  424,  424,  441,  436,
      437,  251,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  438,  438,  438,  438,  442,  438,

      155,  443,  424,  424,  424,  424,  440,  440,  424,  424,
      424,  441,  441,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  438,  438,  438,  438,  438,
      444,  155,  445,  424,  424,  424,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      424,  438,  438,  446,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  447,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  448,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,    0,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424
    } ;

static const flex_int16_t yy_nxt[1021] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       26,   26,   27,   28,   29,   30,   31,   32,   33,   33,
       33,   33,   33,   33,   33,   34,    8,   35,   36,   33,
       37,   38,   39,   40,   41,   42,   33,   33,   43,   33,
       44,   45,   46,   47,   48,   33,   49,   50,   51,   52,
       53,   54,   33,   33,   33,   55,   56,   57,   58,   60,
       61,   60,   61,   63,   64,   63,   64,   69,   71,   74,
       77,   79,   65,  423,   65,   81,   81,   81,   81,   81,
       82,  113,   80,   78,  102,   83,   72,   96,   97,   99,

      100,  188,  123,  114,   84,  189,  124,   75,   70,   85,
      103,   86,   86,   86,   86,  104,  206,  140,  105,  207,
      111,  125,  422,   87,   88,  106,   89,  119,   90,  112,
      141,  127,  115,   91,  120,   92,  107,   87,   88,   87,
      116,  421,  117,  108,   89,  118,  109,  128,  420,  110,
      129,  142,  143,  131,  171,  171,   93,   85,  148,   94,
       94,   94,   94,   94,  132,  133,  419,  134,  203,  135,
      136,   87,   88,  204,   89,  418,  137,  180,  181,  138,
      213,   95,  194,  195,  417,   87,   88,   87,  214,   70,
      416,  415,   89,  150,  148,  148,  151,  156,  156,  156,

      157,   86,   86,   86,   86,  152,  152,  152,  153,   81,
       81,   81,   81,   81,  414,  161,  161,  161,  161,  161,
      399,  159,  160,   91,  154,   70,   70,   87,  162,  151,
      220,  148,  221,  151,  400,  159,  160,  159,  412,  158,
      151,   87,  162,   87,  151,  151,  151,  155,  163,  163,
      163,  163,  166,  215,  166,  237,  347,  167,  168,  168,
      168,  168,   70,  164,   94,   94,   94,   94,   94,  237,
      165,  237,  216,  224,  225,  226,  217,  148,  276,  411,
      277,  164,  148,  224,  225,  226,   95,  424,  410,  153,
      153,  153,  153,   74,  227,  227,  227,  227,  409,  408,

       74,  241,  157,  157,  157,  157,  407,  406,   70,  229,
      229,  229,  229,   70,  148,  231,  405,  231,  243,  244,
      232,  233,  233,  233,  233,  245,  228,  228,  228,  228,
      228,  161,  161,  161,  161,  161,  243,  228,  228,  228,
      244,  404,  403,   87,  162,   70,  401,  159,  398,  228,
      228,  228,  228,  228,  228,  397,  396,   87,  162,   87,
      234,  159,  234,  159,  395,  235,  236,  236,  236,  236,
      163,  163,  163,  163,  163,  163,  163,  163,  167,  168,
      168,  168,  168,  250,  244,  164,  238,  238,  238,  238,
      238,  394,  165,  393,  246,  246,  165,  392,  237,  391,

      243,  244,  390,  164,  244,  244,  389,  252,  239,  247,
      296,  297,  237,  298,  237,  381,  248,  388,  243,  387,
      300,  297,  244,  298,   87,  244,  386,  247,  232,  233,
      233,  233,  233,  235,  236,  236,  236,  236,   87,  385,
       87,  244,  246,  246,  299,  380,  424,  308,  303,  303,
      303,  303,  303,  379,  299,  301,  301,  301,  301,  301,
      159,  354,  244,  378,  248,  377,  301,  301,  301,  376,
      304,  375,  374,  373,  159,  354,  159,  354,  301,  301,
      301,  301,  301,  301,  305,  305,  305,  305,  305,  238,
      238,  238,  238,  238,  296,  297,   87,  298,  372,  371,

      370,  237,  369,  368,  367,  366,  306,  241,  246,  246,
       87,  239,   87,  296,  297,  237,  298,  237,  238,  238,
      238,  238,  238,  247,  243,  244,  424,  309,  299,  309,
      248,  245,  310,  311,  311,  311,  311,  365,  250,  244,
      239,  247,  243,  424,  424,  313,  244,  299,  364,  424,
      363,  346,  297,  244,  298,  243,  244,  362,  326,  308,
      244,  424,  252,  361,  360,  424,  424,  424,  349,  349,
      349,  350,  359,  243,  244,  296,  297,  244,  298,  303,
      303,  303,  303,  303,  424,  299,  358,  424,  424,  357,
      345,  159,  344,  308,  303,  303,  303,  303,  303,  343,

      342,  304,  341,  340,  339,  159,  338,  159,  424,  299,
      351,  352,  352,  352,  352,  352,  304,  310,  311,  311,
      311,  311,  352,  352,  352,  195,  337,  244,  305,  305,
      305,  305,  305,  313,  352,  352,  352,  352,  352,  352,
       87,  305,  305,  305,  305,  305,  424,  336,  244,  335,
      306,  334,  313,  333,   87,  332,   87,  355,  355,  355,
      355,  355,  331,  306,  330,  296,  297,  424,  298,  354,
      296,  297,  329,  298,  296,  297,  328,  298,  327,  356,
      326,  325,  289,  354,  324,  354,  323,  322,  321,  382,
      382,  382,  382,  320,  296,  297,  319,  298,  318,  299,

      317,  316,  296,  297,  299,  298,  315,  314,  299,  383,
      383,  383,  383,  355,  355,  355,  355,  355,   74,  294,
      293,  292,  355,  355,  355,  355,  355,  291,  299,  151,
      151,  151,  151,  151,  354,  356,  299,  290,  289,  288,
      151,  151,  151,  287,  356,  286,  296,  297,  354,  298,
      354,  285,  151,  151,  151,  151,  151,  151,  284,  283,
      282,  383,  383,  383,  383,  281,  280,  279,  278,  275,
      274,  273,  272,  271,  270,  195,  269,  268,  267,  266,
      299,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   62,   62,   62,   62,   62,   62,   62,   62,   62,

       62,   68,  265,   68,   68,   68,   68,   68,   68,   68,
       68,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,  101,  101,  101,  101,  101,  101,   73,  264,   73,
      263,  262,  261,  260,   73,  170,  170,  170,  173,  173,
      173,  230,  230,  240,  240,  242,  242,  242,  259,  242,
      242,  249,  249,  251,  251,  251,  195,  251,  251,  295,
      295,  295,  295,  295,  295,  295,  295,  295,  295,  302,
      302,  307,  307,  258,  257,  307,  312,  312,  195,  256,
      312,  348,  255,  348,  254,  253,  223,  222,  348,  353,
      353,  384,  384,   73,   73,  402,  402,  413,  413,  348,

      348,  219,  218,  212,  211,  210,  209,  208,  205,  202,
      201,  200,  199,  198,  197,  196,  193,  192,  191,  190,
      187,  186,  185,  184,  183,  182,  179,  178,  177,  176,
      175,  174,  172,  169,   74,  149,  147,  146,  145,  144,
      139,  130,  126,  122,  121,   98,   76,   67,   66,  424,
        7,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424
    } ;

static const flex_int16_t yy_chk[1021] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,    5,    5,    6,    6,   13,   15,   16,
       20,   22,    5,  422,    6,   23,   23,   23,   23,   23,
       24,   41,   22,   20,   37,   24,   15,   29,   29,   31,

       31,  114,   46,   41,   24,  114,   46,   16,   13,   25,
       37,   25,   25,   25,   25,   38,  130,   53,   38,  130,
       40,   46,  420,   25,   25,   38,   25,   43,   25,   40,
       53,   48,   42,   25,   43,   25,   39,   25,   25,   25,
       42,  418,   42,   39,   25,   42,   39,   48,  416,   39,
       48,   54,   54,   50,   92,   92,   25,   26,   68,   26,
       26,   26,   26,   26,   50,   50,  414,   50,  128,   50,
       51,   26,   26,  128,   26,  411,   51,  107,  107,   51,
      136,   26,  120,  120,  410,   26,   26,   26,  136,   68,
      409,  406,   26,   70,  150,  151,   70,   75,   75,   75,

       75,   91,   91,   91,   91,   70,   70,   70,   70,   81,
       81,   81,   81,   81,  405,   85,   85,   85,   85,   85,
      379,   81,   81,   91,   70,  150,  151,   85,   85,   70,
      141,  227,  141,   70,  379,   81,   81,   81,  401,   75,
       70,   85,   85,   85,   70,   70,   70,   70,   86,   86,
       86,   86,   88,  138,   88,  167,  298,   88,   88,   88,
       88,   88,  227,   86,   95,   95,   95,   95,   95,  167,
       86,  167,  138,  149,  149,  149,  138,  152,  204,  400,
      204,   86,  153,  224,  224,  224,   95,  298,  399,  152,
      152,  152,  152,  156,  153,  153,  153,  153,  398,  397,

      157,  170,  156,  156,  156,  156,  396,  395,  152,  157,
      157,  157,  157,  153,  155,  160,  392,  160,  170,  170,
      160,  160,  160,  160,  160,  170,  155,  155,  155,  155,
      155,  161,  161,  161,  161,  161,  170,  155,  155,  155,
      170,  387,  385,  161,  161,  155,  380,  232,  377,  155,
      155,  155,  155,  155,  155,  373,  371,  161,  161,  161,
      162,  232,  162,  232,  370,  162,  162,  162,  162,  162,
      163,  163,  163,  163,  165,  165,  165,  165,  166,  166,
      166,  166,  166,  173,  241,  163,  168,  168,  168,  168,
      168,  369,  163,  368,  171,  171,  165,  365,  168,  364,

      173,  173,  363,  163,  250,  241,  362,  173,  168,  171,
      225,  225,  168,  225,  168,  347,  171,  361,  173,  360,
      226,  226,  173,  226,  235,  250,  359,  171,  231,  231,
      231,  231,  231,  234,  234,  234,  234,  234,  235,  357,
      235,  240,  248,  248,  225,  344,  347,  240,  233,  233,
      233,  233,  233,  343,  226,  228,  228,  228,  228,  228,
      233,  310,  240,  342,  248,  341,  228,  228,  228,  340,
      233,  338,  337,  336,  233,  310,  233,  310,  228,  228,
      228,  228,  228,  228,  236,  236,  236,  236,  236,  238,
      238,  238,  238,  238,  295,  295,  236,  295,  335,  334,

      333,  238,  332,  331,  329,  328,  236,  242,  246,  246,
      236,  238,  236,  296,  296,  238,  296,  238,  239,  239,
      239,  239,  239,  246,  242,  242,  245,  244,  295,  244,
      246,  242,  244,  244,  244,  244,  244,  327,  251,  249,
      239,  246,  242,  245,  245,  249,  242,  296,  325,  252,
      324,  297,  297,  307,  297,  251,  251,  323,  322,  307,
      249,  245,  251,  321,  320,  245,  252,  252,  299,  299,
      299,  299,  316,  251,  307,  300,  300,  251,  300,  303,
      303,  303,  303,  303,  252,  297,  315,  308,  252,  314,
      293,  303,  292,  308,  304,  304,  304,  304,  304,  288,

      287,  303,  285,  284,  283,  303,  282,  303,  308,  300,
      299,  301,  301,  301,  301,  301,  304,  309,  309,  309,
      309,  309,  301,  301,  301,  281,  280,  312,  305,  305,
      305,  305,  305,  312,  301,  301,  301,  301,  301,  301,
      305,  306,  306,  306,  306,  306,  313,  279,  312,  278,
      305,  277,  313,  276,  305,  275,  305,  311,  311,  311,
      311,  311,  274,  306,  273,  346,  346,  313,  346,  311,
      348,  348,  271,  348,  349,  349,  270,  349,  269,  311,
      268,  267,  266,  311,  265,  311,  264,  262,  261,  349,
      349,  349,  349,  260,  350,  350,  259,  350,  258,  346,

      256,  255,  383,  383,  348,  383,  254,  253,  349,  350,
      350,  350,  350,  356,  356,  356,  356,  356,  229,  223,
      222,  221,  355,  355,  355,  355,  355,  220,  350,  352,
      352,  352,  352,  352,  355,  356,  383,  218,  216,  215,
      352,  352,  352,  214,  355,  213,  382,  382,  355,  382,
      355,  212,  352,  352,  352,  352,  352,  352,  211,  210,
      209,  382,  382,  382,  382,  208,  207,  206,  205,  203,
      202,  201,  200,  198,  197,  196,  194,  192,  191,  190,
      382,  425,  425,  425,  425,  425,  425,  425,  425,  425,
      425,  426,  426,  426,  426,  426,  426,  426,  426,  426,

      426,  427,  189,  427,  427,  427,  427,  427,  427,  427,
      427,  428,  428,  428,  428,  428,  428,  428,  428,  428,
      428,  429,  429,  429,  429,  429,  429,  430,  188,  430,
      187,  186,  185,  184,  430,  431,  431,  431,  432,  432,
      432,  433,  433,  434,  434,  435,  435,  435,  183,  435,
      435,  436,  436,  437,  437,  437,  182,  437,  437,  438,
      438,  438,  438,  438,  438,  438,  438,  438,  438,  439,
      439,  440,  440,  181,  180,  440,  441,  441,  179,  178,
      441,  442,  177,  442,  176,  175,  143,  142,  442,  443,
      443,  444,  444,  445,  445,  446,  446,  447,  447,  448,

      448,  140,  139,  135,  134,  133,  132,  131,  129,  127,
      126,  125,  124,  123,  122,  121,  118,  117,  116,  115,
      113,  112,  111,  110,  109,  108,  106,  105,  104,  103,
      102,  100,   93,   90,   73,   69,   65,   64,   61,   56,
       52,   49,   47,   45,   44,   30,   19,   12,   11,    7,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,

      424,  424,  424,  424,  424,  424,  424,  424,  424,  424,
      424,  424,  424,  424,  424,  424,  424,  424,  424,  424
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[112] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "java_lexer.l"
#line 2 "java_lexer.l"
    #include<bits/stdc++.h>
    using namespace std;
    #include "test.tab.h"
    int lines=1;
#line 845 "lex.yy.c"

#line 847 "lex.yy.c"

#define INITIAL 0
#define COMMENT1 1
#define COMMENT2 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 46 "java_lexer.l"


#line 1069 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 425 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 951 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "java_lexer.l"
{BEGIN(COMMENT1);}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 49 "java_lexer.l"
{lines++; 
                       BEGIN(INITIAL);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 51 "java_lexer.l"
{lines++; 
                       BEGIN(INITIAL);}                       
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 53 "java_lexer.l"
{lines++; 
                       BEGIN(INITIAL);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "java_lexer.l"
{/*ignore*/}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "java_lexer.l"
{BEGIN(COMMENT2); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "java_lexer.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 59 "java_lexer.l"
{lines++;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "java_lexer.l"
{lines++;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 61 "java_lexer.l"
{lines++;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 62 "java_lexer.l"
{/*ignore*/}           
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "java_lexer.l"
{yylval.lex = new string(yytext); return BOOL_LITERAL;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "java_lexer.l"
{yylval.lex = new string(yytext); return NULL_LITERAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "java_lexer.l"
{yylval.lex = new string(yytext); return INT_LITERAL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "java_lexer.l"
{yylval.lex = new string(yytext); return FLOAT_LITERAL;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 68 "java_lexer.l"
{yylval.lex = new string(yytext); return TEXTBLOCK_LITERAL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "java_lexer.l"
{yylval.lex = new string(yytext); return STRING_LITERAL;}
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 70 "java_lexer.l"
{yylval.lex = new string(yytext); return CHAR_LITERAL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 71 "java_lexer.l"
{yylval.lex = new string(yytext); return FLOATINGPOINTTYPE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 72 "java_lexer.l"
{yylval.lex = new string(yytext); return INTEGRALTYPE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "java_lexer.l"
{yylval.lex = new string(yytext); return THIS;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 74 "java_lexer.l"
{yylval.lex = new string(yytext); return CLASS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 75 "java_lexer.l"
{yylval.lex = new string(yytext); return VOID;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "java_lexer.l"
{yylval.lex = new string(yytext); return BOOLEAN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "java_lexer.l"
{yylval.lex = new string(yytext); return NEW;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "java_lexer.l"
{yylval.lex = new string(yytext); return SUPER;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "java_lexer.l"
{yylval.lex = new string(yytext); return SWITCH;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "java_lexer.l"
{yylval.lex = new string(yytext); return PACKAGE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "java_lexer.l"
{yylval.lex = new string(yytext); return MODULE;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "java_lexer.l"
{yylval.lex = new string(yytext); return REQUIRES;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 83 "java_lexer.l"
{yylval.lex = new string(yytext); return EXPORTS;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 84 "java_lexer.l"
{yylval.lex = new string(yytext); return OPENS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 85 "java_lexer.l"
{yylval.lex = new string(yytext); return TO;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 86 "java_lexer.l"
{yylval.lex = new string(yytext); return USES;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 87 "java_lexer.l"
{yylval.lex = new string(yytext); return PROVIDES;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 88 "java_lexer.l"
{yylval.lex = new string(yytext); return WITH;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 89 "java_lexer.l"
{yylval.lex = new string(yytext); return TRANSITIVE; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 90 "java_lexer.l"
{yylval.lex = new string(yytext); return STATIC;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 91 "java_lexer.l"
{yylval.lex = new string(yytext); return PUBLIC;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 92 "java_lexer.l"
{yylval.lex = new string(yytext); return PROTECTED;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 93 "java_lexer.l"
{yylval.lex = new string(yytext); return PRIVATE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 94 "java_lexer.l"
{yylval.lex = new string(yytext); return ABSTRACT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 95 "java_lexer.l"
{yylval.lex = new string(yytext); return FINAL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 96 "java_lexer.l"
{yylval.lex = new string(yytext); return NATIVE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 97 "java_lexer.l"
{yylval.lex = new string(yytext); return SYNCHRONIZED; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 98 "java_lexer.l"
{yylval.lex = new string(yytext); return TRANSIENT;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 99 "java_lexer.l"
{yylval.lex = new string(yytext); return VOLATILE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 100 "java_lexer.l"
{yylval.lex = new string(yytext); return EXTENDS;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 101 "java_lexer.l"
{yylval.lex = new string(yytext); return THROWS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 102 "java_lexer.l"
{yylval.lex = new string(yytext); return VAR;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 103 "java_lexer.l"
{yylval.lex = new string(yytext); return ASSERT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 104 "java_lexer.l"
{yylval.lex = new string(yytext); return IF;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 105 "java_lexer.l"
{yylval.lex = new string(yytext); return ELSE;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 106 "java_lexer.l"
{yylval.lex = new string(yytext); return CASE;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 107 "java_lexer.l"
{yylval.lex = new string(yytext); return DEFAULT;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 108 "java_lexer.l"
{yylval.lex = new string(yytext); return WHILE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 109 "java_lexer.l"
{yylval.lex = new string(yytext); return DO;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 110 "java_lexer.l"
{yylval.lex = new string(yytext); return FOR;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 111 "java_lexer.l"
{yylval.lex = new string(yytext); return BREAK;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 112 "java_lexer.l"
{yylval.lex = new string(yytext); return CONTINUE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 113 "java_lexer.l"
{yylval.lex = new string(yytext); return RETURN;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "java_lexer.l"
{yylval.lex = new string(yytext); return THROW;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 115 "java_lexer.l"
{yylval.lex = new string(yytext); return TRY;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "java_lexer.l"
{yylval.lex = new string(yytext); return CATCH;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 117 "java_lexer.l"
{yylval.lex = new string(yytext); return FINALLY;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 118 "java_lexer.l"
{yylval.lex = new string(yytext); return INSTANCEOF;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "java_lexer.l"
{yylval.lex = new string(yytext); return EQUALTO;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 120 "java_lexer.l"
{yylval.lex = new string(yytext); return PLUSET;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 121 "java_lexer.l"
{yylval.lex = new string(yytext); return MINUSET;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 122 "java_lexer.l"
{yylval.lex = new string(yytext); return MULTET;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 123 "java_lexer.l"
{yylval.lex = new string(yytext); return DIVET;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 124 "java_lexer.l"
{yylval.lex = new string(yytext); return ANDET;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 125 "java_lexer.l"
{yylval.lex = new string(yytext); return LT;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 126 "java_lexer.l"
{yylval.lex = new string(yytext); return GT;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 127 "java_lexer.l"
{yylval.lex = new string(yytext); return LEQ;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 128 "java_lexer.l"
{yylval.lex = new string(yytext); return GEQ;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 129 "java_lexer.l"
{yylval.lex = new string(yytext); return LEFTSHIFT;}  
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 130 "java_lexer.l"
{yylval.lex = new string(yytext); return RIGHTSHIFT;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 131 "java_lexer.l"
{yylval.lex = new string(yytext); return THREEGREAT;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 132 "java_lexer.l"
{yylval.lex = new string(yytext); return PLUS;}   
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 133 "java_lexer.l"
{yylval.lex = new string(yytext); return MINUS;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 134 "java_lexer.l"
{yylval.lex = new string(yytext); return MULT;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 135 "java_lexer.l"
{yylval.lex = new string(yytext); return DIVIDE;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 136 "java_lexer.l"
{yylval.lex = new string(yytext); return MODULO;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 137 "java_lexer.l"
{yylval.lex = new string(yytext); return INCREMENT;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 138 "java_lexer.l"
{yylval.lex = new string(yytext); return DECREMENT;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 139 "java_lexer.l"
{yylval.lex = new string(yytext); return TILDE;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 140 "java_lexer.l"
{yylval.lex = new string(yytext); return NOT;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 141 "java_lexer.l"
{yylval.lex = new string(yytext); return QUEST;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 142 "java_lexer.l"
{yylval.lex = new string(yytext); return COLON;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 143 "java_lexer.l"
{yylval.lex = new string(yytext); return OR;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 144 "java_lexer.l"
{yylval.lex = new string(yytext); return AND;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 145 "java_lexer.l"
{yylval.lex = new string(yytext); return BITOR;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 146 "java_lexer.l"
{yylval.lex = new string(yytext); return BITAND;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 147 "java_lexer.l"
{yylval.lex = new string(yytext); return POW;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 148 "java_lexer.l"
{yylval.lex = new string(yytext); return EQ;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 149 "java_lexer.l"
{yylval.lex = new string(yytext); return NEQ;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 150 "java_lexer.l"
{yylval.lex = new string(yytext); return DOT;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 151 "java_lexer.l"
{yylval.lex = new string(yytext); return LCB;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 152 "java_lexer.l"
{yylval.lex = new string(yytext); return RCB;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 153 "java_lexer.l"
{yylval.lex = new string(yytext); return LSB;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 154 "java_lexer.l"
{yylval.lex = new string(yytext); return RSB;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 155 "java_lexer.l"
{yylval.lex = new string(yytext); return LRB;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 156 "java_lexer.l"
{yylval.lex = new string(yytext); return RRB;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 157 "java_lexer.l"
{yylval.lex = new string(yytext); return COMMA;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 158 "java_lexer.l"
{yylval.lex = new string(yytext); return SEMICOLON;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 159 "java_lexer.l"
{yylval.lex = new string(yytext); return IDENTIFIER;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 160 "java_lexer.l"
{/*ignore whitespace*/}
	YY_BREAK
case 109:
/* rule 109 can match eol */
YY_RULE_SETUP
#line 161 "java_lexer.l"
{/*ignore line terminator*/}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 162 "java_lexer.l"
{cerr<<"Illegal character encountered: Lexical Error "<<strdup(yytext)<<endl; exit(1);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 163 "java_lexer.l"
ECHO;
	YY_BREAK
#line 1701 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT1):
case YY_STATE_EOF(COMMENT2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 425 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 425 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 424);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 163 "java_lexer.l"

